### ISSUE TITLE
Wrap :text option text in own tag

### ISSUE THREAD

**Issue by akaspick** [bokmann/font-awesome-rails#135]
Is there any interest in wrapping the text provided with the :text option in its own tag like a span?  This would allow for easier styling via css like adding margins, etc.

Something like:

```ruby
fa_icon('edit', text: 'Edit') # => <i class="fa fa-edit"></i><span>Edit</span>
```

Now I can add a margin if there's a label and no margin if there is no label via...

```css
.fa {
  margin-right: 0.2rem;
}
.fa:only-child {
  margin-right: 0;
}
```
