### ISSUE TITLE
Font paths lacking asset hash production environment (nginx+unicorn)

### ISSUE THREAD

**Issue by douglascamata** [bokmann/font-awesome-rails#137]
Set-up: unicorn and nginx (serving assets) in production environment.

`font-awesome-rails` generated paths for fonts hadn't the hash in the asset path. I was able to get it working using the CSS fix proposed [here](http://stackoverflow.com/questions/24044660/font-awesome-rails-wont-work-after-deploying-it-looks-like-bad-unicode-charact).

Maybe you should fix the CSS of the gem by using the asset-url helper too.

**Comment by rmm5t** [comment]
Are you sure you're precompiling your assets correctly? It sounds like you might not be precompiling the assets in production mode. What version of Rails? Are you using a separate asset server? Are you using another asset gem that also includes Font Awesome and is breaking the path of the assets here? Did you follow the debugging steps in the [contribution guidelines](https://github.com/bokmann/font-awesome-rails/blob/master/CONTRIBUTING.md) before submitting this issue?

> Maybe you should fix the CSS of the gem by using the asset-url helper too.

Uh, it already does, and it actually does one better by using the more accurate `font_path` helper. 
https://github.com/bokmann/font-awesome-rails/blob/master/app/assets/stylesheets/font-awesome.css.erb#L15

**Comment by douglascamata** [comment]
Sure I was precompiling my assets correctly. I use capistrano recipes to do that and only by overriding that piece of CSS it worked, the app now is generating links with the hash included. The expected behavior of this gem is to generate the links with or without that hash? 

I was using Rails 4.1, serving my assets from an nginx instance in the same machine as I'm running unicorn, no other asset gem, no cache involved (using the 'Disable cache' of Chrome developer tools)...

**Comment by rmm5t** [comment]
Yes, the expected behavior of this gem is that it generates links in the
CSS with the signature hash, cache-busting suffix. I personally use it on a
half a dozen projects ranging from Rails 3.2 to Rails 4.2, and the assets
are generated as expected and the CSS font paths are as expected.

It sounds like you might have another gem or CSS that was also trying to
reference font awesome that overrode the CSS from font-awesome-rails, but
until you following our suggestions/steps in our contribution/debugging
guidelines, I can't offer much help.

**Comment by zrisher** [comment]
Experiencing the same issue, with  `*= require font-awesome` in my `application.css`, `config.assets.digest = true` in my environment, and `font-awesome-rails-4.3.0.0` & `rails-4.2.0` I get font paths generated that lack the digest part of their url. They're compiled into public/assets just fine, but the css paths are just `/assets/fontawesome-webfont.woff?v=4.3.0`. All my other assets using path helpers are processed correctly.

**Comment by rmm5t** [comment]
@zrisher. I'm going to tell you the exact same thing that I told @douglascamata. If you don't follow the debugging steps in our [contribution guidelines](https://github.com/bokmann/font-awesome-rails/blob/master/CONTRIBUTING.md), I can't provide much help.  

**Afterall, before submitting an issue, GitHub warns you to read the [Contribution Guidelines](https://github.com/bokmann/font-awesome-rails/blob/master/CONTRIBUTING.md) before opening the issue.** 

Some quick examples of what might be wrong.

1. There might be other gems or project assets that reference broken Font Awesome assets (this is why the guidelines ask you to provide a `bundle list`).
2. There might be files in your `public/assets` directory of your repository that are overriding things. 
3. Assets precompilation might be triggered incorrectly (i.e. Just because you claim to rely on capistrano doesn't necessarily guarantee anything).
4. Is `config.assets.digest = true` in your `development.rb` and `production.rb`??

**Here is what this gem generates with a proper assets precompilation on Rails 4.2** (this was taken from one of my live projects). Again, we're already using the `font_path` Rails helper to generate this CSS.

```css
/*!
 *  Font Awesome 4.3.0 by @davegandy - http://fontawesome.io - @fontawesome
 *  License - http://fontawesome.io/license (Font: SIL OFL 1.1, CSS: MIT License)
 */
/* FONT PATH
 * -------------------------- */
@font-face {
  font-family: 'FontAwesome';
  src: url("/assets/fontawesome-webfont-245085072b75421dcf3905ea1d3eeeec.eot?v=4.3.0");
  src: url("/assets/fontawesome-webfont-245085072b75421dcf3905ea1d3eeeec.eot?#iefix&v=4.3.0") format("embedded-opentype"), url("/assets/fontawesome-webfont-011b450c29c698726739dec9c520eccd.woff2?v=4.3.0") format("woff2"), url("/assets/fontawesome-webfont-d91398710edfa0f4a3b8e3a33a313757.woff?v=4.3.0") format("woff"), url("/assets/fontawesome-webfont-2751d584a0c31f9b2a2f6c6d25b03b82.ttf?v=4.3.0") format("truetype"), url("/assets/fontawesome-webfont-c93bed61f9efdb1750df2c4e53d536cb.svg?v=4.3.0#fontawesomeregular") format("svg");
  font-weight: normal;
  font-style: normal;
}
```

Furthermore, if you're using the proper defaults for Rails 4.2, the signature hash suffixes should even show up in development mode, not just when you precompile to production.

Can someone point me to a CSS file in the wild that claims to use font-awesome-rails in production, but the font assets urls are missing the signature hash suffix?
