### ISSUE TITLE
Version number as URL parameter breaks Content-Type detection

### ISSUE THREAD

**Issue by czj** [bokmann/font-awesome-rails#174]
First, sorry if this issue is a dupe, I've check the gem's documentation and previous issues to make to try to find a solution.

-----------

Generated assets include a version number at the number like :

```css
@font-face {
    font-family: 'FontAwesome';
    src: url("/assets/fontawesome-webfont-50bbe9192697e791e2ee4ef73917aeb1b03e727dff08a1fc8d74f00e4aa812e1.eot?v=4.6.3");
 }
```

A page monitoring service we use detected that the Content-Type for this particular asset is returned as `application/octet-stream` instead of `application/font-woff2` for other font assets we use.

As this gem is made to be used with Rails and Sprockets, which generates checksum/hash suffixed assets during compilation that allows for efficient caching, is there a reason for this version parameter ?

Thanks a lot.
